export const meta = {
  name: 'punch-figma-pack',
  description: 'Build the full PunchApp Figma pack: tokens and styles, the design system page, native components, every machine and phone section as variant component sets, composed screens, animation, looks and cover',
  phases: [
    { title: 'Tokens', detail: 'variables with four modes, text and effect styles' },
    { title: 'Pages', detail: 'design system, components, machine, phone, animation, looks, cover' },
    { title: 'Review', detail: 'screenshot every page, fix, and a final check' },
  ],
}

const P = 'C:/Claude Database/punch-exercise'
const FILE = 'j1cOyUKz9Gys3njKSUve6L'
const HOUSE = `
THE TASK: the user asked for a FULL Figma pack of the PunchApp showcase (a design task for Robotenc), "includes design system, components, machine page, mobile app, animation page, and all variants we have for every page and components ... a cover page at first ... separated by pages". You build one part of it.
FIGMA FILE: key ${FILE} (https://www.figma.com/design/${FILE}), in the user's Farhan Personal team. Pages (id): Cover 0:1, Design system 1:2, Components 1:3, Machine screens 1:4, Machine sections 1:5, Mobile app 1:6, Mobile sections 1:7, Animation 1:8, Looks 1:9. Do not create or rename pages.
FIGMA TOOLS: the Figma MCP tools are deferred: load them first with ToolSearch "select:mcp__8bb2429e-ce99-4151-a843-154d5883e10a__use_figma,mcp__8bb2429e-ce99-4151-a843-154d5883e10a__upload_assets,mcp__8bb2429e-ce99-4151-a843-154d5883e10a__get_screenshot,mcp__8bb2429e-ce99-4151-a843-154d5883e10a__get_metadata,mcp__8bb2429e-ce99-4151-a843-154d5883e10a__get_figma_skill". BEFORE your first use_figma call, read the skill with get_figma_skill uri "skill://figma/figma-use/SKILL.md" (and for components "skill://figma/figma-generate-library/SKILL.md"), follow it, and pass skillNames "resource:figma-use" on every use_figma call. Key rules: plain JS with top-level await and return (return every created node id); await figma.setCurrentPageAsync(page) ONCE per call (get the page with figma.getNodeByIdAsync(id)); colours 0 to 1; fills are arrays you reassign; load fonts before any text (families available: Barlow and Barlow Condensed (styles "Regular", "Medium", "SemiBold", "Bold", "ExtraBold", "Black"), Big Shoulders Display ("Bold", "ExtraBold", "Black"), Archivo Black ("Regular"), Sora, Anton, Poppins, Inter ("Semi Bold" with a space), Chakra Petch, Orbitron); never figma.notify, createImageAsync, loadAllPagesAsync or setPluginData; each use_figma script up to about 50,000 characters; keep each call to a coherent batch and verify with node.screenshot() or get_screenshot after each milestone. Known traps: instance children cannot be moved (x/y) but can be resized, hidden and have fills or text changed; resize() pins sizing to FIXED; emptying a GROUP deletes it; cloning a verified frame is cheaper than rebuilding; a right-aligned text box still positions by its left edge; an agent that died leaves half-built nodes, so ALWAYS list what already exists on your page first and reconcile by name (never duplicate).
IMAGES: raster images cannot be created from code. To put an image on a node: 1) create the target frames or rectangles with use_figma (sized to the image's design size) and return their ids in order; 2) call upload_assets with count N (at most 60) and nodeIds [the ids, same order] and scaleMode "FILL"; 3) write a JSON list [{ "file": "<path relative to ${P}>", "url": "<submitUrl>" }, ...] in the same order and run \`node tools/figma-upload.mjs <pairs.json> <results.json>\` from ${P}: it POSTs them and returns each imageHash. URLs expire in 10 minutes, so upload right after asking. An imageHash can be reused on any other node as { type: 'IMAGE', imageHash, scaleMode: 'FILL' } in use_figma, with no new upload. SVGs (logos, icons) uploaded WITHOUT nodeIds become editable vector frames on the Cover page (0:1): move them to your page with appendChild right after, and never leave them on the Cover.
CAPTURES: everything was rendered from the running showcase into ${P}/build/figma/cap/, described by manifests ${P}/build/figma/cap/manifest-machine.json, manifest-phone.json, manifest-looks.json, manifest-beats.json, manifest-extras.json. Entries: kind "section" { surface, page, pageLabel, sec, secLabel, i, name, file, w, h, x, y, whole } (one design of one section: machine files are 1:1 glass pixels, 1080 wide, x and y relative to the 1080 x 3840 screen; phone files are 2x, positions x and y in phone points relative to the page's scroll content, so the Figma frame for a phone section is w/2 x h/2 points; whole=true means the design is an overlay or full-bleed, captured as the whole screen); kind "screen" (the whole screen as built: machine 1080 x 3840 jpg, phone 880 x 1912 png = 440 x 956 points); kind "base" (a machine screen with its sections hidden; for the phone a list of slices { file, top } with the page's sections hidden and a transparent ground, and the page's full height); kind "chrome" (machine header mheader and sponsor strip, 5 designs each with x, y; phone status bar and the tab bar's 5 designs); kind "background" (8 grounds per surface); kind "look" (screens in the four looks); kind "beat" (the flow, phone and machine at each beat, with a caption); kind "ds" (the showcase's design system tab in slices). Key frames of the score reveal clip are in cap/clip (cut-*.jpg 1920 x 1080, glass-*.jpg 540 x 1920, reveal-live-960.gif). Open any image with the Read tool to look at it.
THE PRODUCT: PunchApp is a boxing strength machine in a Dubai mall: a 1080 x 3840 portrait glass (screens: Home, Leaderboard, Scan, Punch now, Reading, Result, Big score, New record) and a phone app (iPhone 17 Pro Max 440 x 956; pages: Home, Scan, Connect, Connected, Punch, Top up, Checkout, Paid, Payment failed, Your hit, Reel, Saved, Leaderboard, Feed, Profile). Four looks: Arena and Reference, each dark and light. The brand red is #EB1110; the sponsor is Monster Energy (green #95D600 on black). The showcase is in ${P}/showcase (tokens in styles.css :root blocks for the four looks and mobile.css .m-app blocks; spacing in mpages/_shared.css and mscreens/_space.css); it runs at http://localhost:5770.
FIGMA CRAFT: this pack is handed to designers. Name every layer and component meaningfully ("Machine / Home / Top ad", variant property "Design=Monster can"; a variant value can never contain a comma or an equals sign, because Figma reads those as separators, so drop commas from design names); set component descriptions; give every page a clear layout: a page title block at the top left (page name, one line on what is here), then labelled groups in Figma SECTION nodes (figma.createSection()) laid out left to right in reading order with 200 px gutters; nothing overlapping; frames never at 0,0 by accident. Copy you write follows the house rules: no em or en dashes, no emoji, British spelling, short and specific.
HOW TO WORK: other agents build other pages of the same file at the same time: touch ONLY your pages. The Figma MCP has rate limits: prefer fewer, larger, well-tested scripts over many tiny ones, and if a call is rate limited, wait a minute and retry. Record every id you create that others may need in ${P}/build/figma/state/LOG_NAME.json and append a short progress entry to ${P}/build/figma/state/LOG_NAME.md after each finished piece (what, node ids, how verified), so a cut-off run can resume. Verify each page with get_screenshot of the page's main frames (maxDimension 2000) and LOOK at them.
`

const TOKENS = `
YOUR PART: the design tokens and styles (no page layout). 1) Read the showcase's tokens: styles.css (the four :root blocks: default is Arena dark, then [data-variant="reference"], [data-appearance="light"], and both) and mobile.css (the .m-app look blocks), mpages/_shared.css and mscreens/_space.css. Where a value is a color-mix or a variable chain, resolve it in the running showcase (for each look: window.showcase.theme(v); window.showcase.appearance(a); then getComputedStyle(document.documentElement) and getComputedStyle(document.getElementById('mApp')).getPropertyValue(name)) using node tools/shoot.mjs with an eval plan; skip gradients (note them). Write the resolved table to ${P}/build/figma/state/tokens-values.json.
2) In Figma create variable collections: "Color / Machine" and "Color / Phone", each with four modes named "Arena dark", "Arena light", "Reference dark", "Reference light", holding the colour tokens with clear slash names (for example "ink/1", "ground", "surface/hi", "red", "on-red", "line"), scopes set properly (fills, strokes, text); "Space" (the --m-* and --ms-* scales as FLOAT with GAP and WIDTH_HEIGHT scopes, grouped "phone/..." and "machine/..."), "Radius" (the radii in use); and a "Brand" collection with single-mode primitives (Red #EB1110, Monster green #95D600, Monster black, Ink, Paper) that the semantic colours alias where they match.
3) Text styles for both surfaces from the CSS in use (machine: display numbers and headings in Big Shoulders Display, labels in Barlow Condensed, body in Barlow; Reference's Archivo Black and Sora; phone: titles, headings, body, captions, labels, numbers), named "Machine/Display/XL" and so on, with real sizes, line heights and letter spacing from the CSS; effect styles for the glows and shadows used (red glow, card lift).
4) Write every collection id, mode id, variable id (by name) and style id to ${P}/build/figma/state/tokens.json. Verify with a read-only use_figma that lists the collections, modes and counts. LOG_NAME is tokens.`

const DSPAGE = `
YOUR PART: the "Design system" page (1:2). Read ${P}/build/figma/state/tokens.json first (variables and styles made by the tokens agent). Build, in SECTION nodes left to right:
1) Cover strip: "Design system", what it covers, the four looks.
2) Colour: for each collection (Machine, Phone) a swatch board per mode (four columns: set each column frame's explicit variable mode with setExplicitVariableModeForCollection so one set of swatch components shows each look), every swatch filled by its variable (setBoundVariableForPaint) and labelled with its name and resolved hex.
3) Type: a specimen for every text style, applied (textStyleId), with its size and line height.
4) Space and radius: the scales drawn as bars and corner samples bound to the variables.
5) Brand: the logo marks (upload the SVGs in ${P}/showcase/assets/logos/*.svg and ${P}/showcase/assets/brand/*.svg as vectors, then make each a component "Logo / <name>") and the Monster Energy kit (the captured sponsor strips and top ads as references).
6) Icons: every Lucide icon the showcase uses (the SVGs in ${P}/showcase/assets/icons/lucide/*.svg; upload in batches of 60), each turned into a component "Icon / <name>" at 24 x 24 with its stroke colour bound to a colour variable, laid out in a labelled grid.
7) Backgrounds: the eight grounds for each surface (manifest kind "background"), labelled.
8) As built: the showcase's own design system tab (manifest-extras.json kind "ds": its slices stacked into one tall frame "Showcase design system, as built", 1440 wide) as a reference at the far right.
LOG_NAME is ds.`

const COMPONENTS = `
YOUR PART: the "Components" page (1:3): NATIVE components (vectors and text, not screenshots), bound to the variables and text styles in ${P}/build/figma/state/tokens.json, each a component set with real variant properties and a description. Read the showcase's CSS for exact sizes, radii, paddings and states (mobile.css, mpages/*.css, pay.css, nav.css, qr.css, styles.css) and LOOK at the captures (cap/phone/..., cap/machine/...) to match them. Build at least:
Phone: Button (Type=Primary red, Glass, Ghost, Monster green; State=Default, Pressed, Disabled; with and without icon); Icon button (44, glass); Credits chip; Chip (red, glass); Segmented control (2 and 3 options, one selected); Stepper (minus, value, plus); Avatar (sizes 32, 44, 64, with ring); Page header (Title only, Title with icon button, Place line and title); Leaderboard row (rank, avatar, name, city, score with smaller decimals, delta; states You and Default); Machine card (venue photo, name, distance); Tab bar (the five styles Red glow, Tab bar, Dock, Notch, Minimal, each with Home, Ranks, Punch logo, Feed, Profile; Current=Home, Ranks, Punch, Feed, Profile); Bottom sheet (grab handle, title, body, primary button); Toast; Score (whole number plus smaller decimals, sizes S, M, L, XL).
Machine: QR tile (the one QR style: the phone app's code on its glass tile with rim, red glow and scan line, drawn natively from the real 25 x 25 matrix in ${P}/showcase/qr.js window.QR_MATRIX as rectangles merged into one vector, sizes 217 and 640; State=Waiting, Scanning, Found with the tick); Punch again call to action; Machine header (upload the 5 captured header designs, manifest-machine kind chrome sec mheader, as image variants "Design=<name>"); Sponsor strip (the 5 captured strips, image variants); Score plate (whole number plus smaller decimals at glass sizes); Rank tile; Background (the 8 captured machine grounds as image variants).
Each component bound to variables so switching a frame's variable mode (Arena dark, Arena light, Reference dark, Reference light) re-colours it; show each set once in Arena dark and once in Arena light (a wrapper frame with an explicit mode) to prove it. Lay the page out in SECTION nodes: Phone, Machine, Shared, each with labels. LOG_NAME is components.`

const MACHINE = `
YOUR PART: the machine: the "Machine sections" page (1:5) and the "Machine screens" page (1:4). Read ${P}/build/figma/cap/manifest-machine.json and manifest-extras.json.
1) Machine sections (1:5): for every screen in order (Home, Leaderboard, Scan, Punch now, Reading, Result, Big score, New record) a SECTION node "<Screen>" holding one COMPONENT SET per section: its variants are the section's designs (from kind "section", one component per design, named "Design=<name>", sized w x h in glass pixels, filled with the capture), component set named "Machine / <Screen> / <secLabel>", laid out as a row with the design names readable (add a text label above each set with the section's name and "five designs" style note if you like, no numerals as decoration). Also a SECTION "Every screen" with component sets for the header (5), the sponsor strip (5) and the background (8) from kind "chrome" and "background" (reuse the components page's sets if they already exist there: check first, and do not duplicate; if they exist, use instances of them).
2) Machine screens (1:4): one FRAME per screen, 1080 x 3840, named "<Screen>", in flow order left to right with 240 px gaps and a label above each: fill it with the screen's base image (kind "base", sections hidden; the Result's base is in manifest-extras.json), then place an INSTANCE of each section's component set at its captured x and y (the first design, i = 0), and the header and sponsor strip instances at their captured positions, so each screen reads exactly as built AND any section's design can be swapped from the instance's variant property. Sections captured "whole" (overlays) go in as full-screen instances at 0,0 above the base. Verify every composed screen against its as-built capture (kind "screen") with get_screenshot and fix any offset. Then lay out a second row with each screen as built (the kind "screen" images, 1080 x 3840) labelled "As built", for reference.
LOG_NAME is machine.`

const PHONE = `
YOUR PART: the phone: the "Mobile sections" page (1:7) and the "Mobile app" page (1:6). Read ${P}/build/figma/cap/manifest-phone.json.
1) Mobile sections (1:7): for every page in order (Home, Scan, Connect, Connected, Punch, Top up, Checkout, Paid, Payment failed, Your hit, Reel, Saved, Leaderboard, Feed, Profile) a SECTION node "<Page>" holding one COMPONENT SET per section: variants are the designs ("Design=<name>"), each component sized w/2 x h/2 points (the captures are 2x) and filled with the capture (a design captured "whole" is a full 440 x 956 screen overlay: keep it as such), named "Phone / <Page> / <secLabel>". Plus a SECTION "Every page": the status bar (1) and the tab bar's five styles as a component set (kind "chrome"), and the eight phone backgrounds (kind "background") as a component set.
2) Mobile app (1:6): one FRAME per page, 440 wide and as tall as the page's content (the base entry's height, at least 956), named "<Page>": the ground is the default background (the first phone background) at the top 440 x 956 plus the Arena dark ground colour below; the page's base slices (sections hidden, transparent) placed at their tops; an INSTANCE of each section's set at its captured x and y (design 0; "whole" overlays not placed in the page frame, but shown in a row of states below); the status bar instance at the top and, for pages with the tab bar (Home, Scan, Your hit, Saved, Leaderboard, Feed, Profile), the tab bar instance pinned to the bottom of the first 956 points. Corner radius 55 on each frame, clip content. Then a second row: each page's first screen as built (kind "screen", 440 x 956) labelled "As built", and a third row: the overlay states (sheets) captured whole.
Verify each page frame against its as-built screen with get_screenshot and fix offsets. LOG_NAME is phone.`

const STORY = `
YOUR PART: the "Animation" page (1:8), the "Looks" page (1:9) and the "Cover" page (0:1).
1) Animation (1:8): the flow as a storyboard from manifest-beats.json: for each beat a pair (the phone screen 440 x 956 and the machine glass scaled to 270 x 960, both from the capture) side by side in a column, with the beat's caption and its moment in the flow under it; beats left to right with arrows between them (lines with an arrow end), titled "One strike, two screens". Wire a prototype: each beat frame navigates to the next ON_CLICK and AFTER_TIMEOUT (1.6 s) with SMART_ANIMATE, starting from the first (set it as the flow starting point, named "The flow"). Below: "The score reveal, as a clip": the key frames in ${P}/build/figma/cap/clip (glass-*.jpg in a row at 270 x 960 each with its time, and cut-*.jpg at 960 x 540) and the animated GIF reveal-live-960.gif as an image fill (GIFs play in Figma prototypes), with a note of the clip's beats and timings (strike 0.8 s, Reading 1.6 s, New record 3.36 s, Big score 5.6 s, the reason 8.14 s, the photo 8.84 s; about ten seconds at 60 fps) and where the MP4 files live (showcase/assets/motion/reveal-live-*.mp4).
2) Looks (1:9): manifest-looks.json: a grid, one column per look (Arena dark, Arena light, Reference dark, Reference light), rows: the machine Home, Result and Big score (540 x 1920) and the phone Home, Punch, Your hit and Leaderboard (440 x 956), each labelled.
3) Cover (0:1): a 1920 x 1080 cover frame "Cover": the project name "PunchApp", the line "Ring the Bell: the score on the glass and the hit on your phone", "A design task for Robotenc", the Robotenc logo (upload ${P}/showcase/assets/brand/robotenc.svg or robotenc-light.svg as a vector), the PunchApp mark (showcase/assets/logos/fist-circle.svg), the date 19 September 2026 and the author Farhan Hosseini, and a key visual: the machine Home screen (cap/machine/screen-default.jpg) standing tall at the right with the phone Home (cap/phone/screen-default.png) in front of it, on a dark ground with the brand red; plus a contents list of the pages (Design system, Components, Machine screens, Machine sections, Mobile app, Mobile sections, Animation, Looks). Set this Cover frame as the file thumbnail if possible (figma.setFileThumbnailNodeAsync). Designed, not templated: one confident composition, no pill labels, no stat cards.
LOG_NAME is story.`

const REVIEW_A = `
YOUR PART: REVIEW AND FIX the Cover, Design system, Components, Animation and Looks pages. Read the logs in ${P}/build/figma/state/*.md. Screenshot every top-level frame and section (get_screenshot, maxDimension 2000), LOOK, and fix what is wrong: overlapping or clipped text, missing images (empty image fills), stray SVG frames left on the Cover, wrong names, components without descriptions or variant properties, variables not bound, frames at 0,0 on top of each other, copy with dashes. Check the Cover reads as a designed cover. Log each fix in ${P}/build/figma/state/review-a.md.`

const REVIEW_B = `
YOUR PART: REVIEW AND FIX the Machine screens, Machine sections, Mobile app and Mobile sections pages. Read the logs in ${P}/build/figma/state/*.md and the manifests. Check: every section of every page has its component set with ALL its designs (count them against the manifests: every design captured must be a variant), images present (no empty fills), composed screens match the as-built captures (get_screenshot and compare with the Read of the capture), instances swap correctly (pick a few, setProperties to another design, screenshot, then set back), names, layout of each page (labels, sections, no overlaps). Fix what is wrong, log each fix in ${P}/build/figma/state/review-b.md.`

const FINAL = `
YOUR PART: the FINAL CHECK of the whole Figma file against the user's ask: a full pack with a cover page first, then design system, components, machine screens, the mobile app, the animation page, and all variants for every page and component, separated by pages. List every page with its top-level contents (a read-only use_figma per page, in parallel), count component sets and variants per page and compare with the manifests, screenshot each page overview, fix remaining gaps, make sure the Cover is the first page and nothing is left on it except the cover, and end with a table: page, what is on it, counts (component sets, variants, frames), state. Log in ${P}/build/figma/state/final.md.`

const run = (log, label, prompt, phaseName, attempt = 1) =>
  agent(HOUSE.split('LOG_NAME').join(log) + '\n' + prompt + '\nWHEN DONE reply with what you built (pages, node ids of the main frames and sets, counts), what you verified, and anything left.',
    { label: attempt === 1 ? label : label + ' (retry)', phase: phaseName })
    .then((r) => (r || attempt > 1 ? r : run(log, label, prompt, phaseName, 2)))

async function pool(tasks, n, phaseName) {
  const out = new Array(tasks.length)
  let next = 0
  await Promise.all(Array.from({ length: n }, async () => {
    while (next < tasks.length) {
      const k = next++
      const t = tasks[k]
      out[k] = await run(t[0], t[1], t[2], phaseName)
      log(`${t[1]}: ${out[k] ? 'done' : 'no result'}`)
    }
  }))
  return out
}

const results = {}
phase('Tokens')
results.tokens = await run('tokens', 'tokens and styles', TOKENS, 'Tokens')
phase('Pages')
const S = [['machine', 'machine sections and screens', MACHINE], ['phone', 'phone sections and app', PHONE], ['ds', 'design system page', DSPAGE], ['components', 'native components', COMPONENTS], ['story', 'animation, looks and cover', STORY]]
const out = await pool(S, 3, 'Pages')
S.forEach((t, i) => { results[t[1]] = out[i] })
phase('Review')
const R = [['review-a', 'review: cover, system, components, animation, looks', REVIEW_A], ['review-b', 'review: machine and mobile pages', REVIEW_B]]
const rv = await pool(R, 2, 'Review')
R.forEach((t, i) => { results[t[1]] = rv[i] })
results.final = await run('final', 'final check', FINAL, 'Review')
return results
