export const meta = {
  name: 'punch-round6',
  description: 'Every page built from sections with at least five designs each, Default pages, one background and one QR style for both surfaces, reels, real photos, spacing',
  phases: [
    { title: 'Build', detail: 'thirteen page builders, four at a time: machine screens, phone pages, shared chrome' },
    { title: 'Finish', detail: 'documents, a new motion clip, a review of each surface' },
    { title: 'Final', detail: 'one last sweep of the whole showcase and the brief' },
  ],
}

const P = 'C:/Claude Database/punch-exercise'
const HOUSE = `
PROJECT: a design showcase for a PunchApp design task done for Robotenc, in ${P}/showcase (vanilla HTML, CSS and JS, no build), served at http://localhost:5770 by \`node tools/serve-showcase.mjs\` (if it does not answer, start it in the background from ${P}). Server-side includes: <!-- include:path --> (nested). Concatenated styles: /sections.css (showcase/sections/*.css), /mscreens.css (showcase/mscreens/*.css), /mpages.css (showcase/mpages/*.css). THE BRIEF the company gave: C:/Users/Farhan Hosseini/Downloads/product-designer-challenge.md.

THE SHOWCASE: four tabs: Mobile app (the phone alone, default), Machine screen (the 1080 x 3840 glass), Animation (the phone and a live embedded machine side by side, Start and Reset under the tabs, the score reveal clip below), Design system. Looks: html[data-variant="arena|reference"] x html[data-appearance="dark|light"] (four looks, every design must work in all four). Logo: <img data-logo-img> takes the chosen mark. Score format html[data-decimals="on|off"]: every score goes through window.PunchFormat (.score(n) text, .scoreHTML(n) markup with the three decimals in <span class="dec">, .width(n), .withDecimals(whole, seed)); re-render on the document "decimals" event.

WHAT THE USER ASKED FOR THIS ROUND (all of it matters):
1. A "Default" page on both surfaces, like a home (phone: the app's home, tab bar "Home"; machine: the glass at rest). The machine's Default also has a Monster Energy ad at the TOP, a different ad from the sponsor strip at the foot.
2. More REAL images and more icons on the phone and the machine.
3. The "How to use the QR code" images must change (new illustrations are in showcase/assets/howto/, see below).
4. Every page on the machine and the phone needs better spacing between items and between groups.
5. Every page has Customise rows for EVERY section it has; switching page switches the rows; every section has AT LEAST FIVE designs (none may have fewer).
6. Customise is accordions: "This screen" (the page's sections), then shared groups (background, chrome, score, theme, logo, phone, glass). (Built.)
7. Animation tab: only Start and Reset under the tabs. (Built.)
8. The task title, the brief button and its line sit under the Robotenc logo. (Built.)
9. Reels: remove the up/down slider with dots on the right; reels scroll without end; add settings and a three dots menu.
10. Remove assets/mscreens/boxer-gym-gold.jpg everywhere and replace it with something better.
11. The Punch now background must be much better. The machine's Scan page must look like the phone app's scan (the phone's QR on its glass tile). One GLOBAL background style for the app and the machine, chosen in Customise.
12. Every QR code, on every design, in the phone app's QR style.

THE SECTION ENGINE (showcase/psec.js, read its header comment): every page is built from sections.
- A section is an element with data-sec="key" data-sec-label="Label" inside its page root (machine: article.mscreen[data-mscreen="KEY"], markup in parts/mscreen-KEY.html; phone: section.m-page[data-page="KEY"], markup in parts/mpage-KEY.html or parts/phone-pay.html). Its designs are its DIRECT children with data-sv="Design name"; the engine shows one (hidden on the rest) and sets data-sv-index and data-sv-name on the section. A section drawn by a script lists data-sv-names="A|B|C|D|E" and renders from window.PSec.get(surface, page, key) (example: the phone leaderboard, parts/mpage-ranks.html #mBoard and mobile.js renderBoard).
- Customise builds its "This screen" rows from these automatically: data-sec-label is the row's name, data-sv the design's name. Names are short and descriptive ("Podium", "Glass tile"), never "Design 3" or "A".
- Events: the machine opens a screen with document event "mscreen" { key, opts }; the phone opens a page with "mpage" { page, from, opts }; a Customise change fires "psec" { surface, page, sec, index, name, el (the design now shown), section }. A page script starts its motion when its page opens, stops it when another opens, and restarts a section when its psec arrives. Scope every query to the ACTIVE design (window.PSec.active(surface, page, key) or the psec detail's el).
- Hooks for testing: window.showcase.mode('mobile'|'machine'|'animation'|'system'), .mscreen(key, opts), .sec(surface, page, key, index), .sections(surface, page), .backdrop(key), .decimals(on), .appearance('dark'|'light'), .theme('arena'|'reference'); window.punchApp.go(page, opts) on the phone.
- Every section needs at least FIVE designs, each a genuinely different composition (not a colour swap). Where a section already exists, its current look (improved) is the first design. Sections stack in the page's own layout; each design must fit its section's room in both phone sizes (iPhone 440 x 956, Android 412 x 915) or on the glass, with nothing clipped or colliding, in all four looks.
- The Result screen (#screen) keeps its older engine (.sec[data-slot] > .vars > .var, app.js SLOTS) and its own Customise rows.
- The old whole-screen designs on the machine flow screens (.msv children with data-name) are RETIRED this round: rebuild each screen as ONE frame with sections, harvesting the existing designs as section designs. When a screen has sections, remove its .msv wrappers (app.js shows a "Layout" row only for screens that still have .msv).

SHARED PIECES, use them, do not re-invent:
- ONE QR STYLE (showcase/qr.js + qr.css): <div class="pqr" data-pqr style="--pqr-size: 640px"></div> is filled on load with the phone app's code on its glass tile (glow, rim, scan line); PunchQR.mount(el) for markup you add later; states .is-scanning and .is-found; data-pqr-glow="off" or data-pqr-scan="off" to drop the glow or line. Every QR on every design uses it; no other QR drawing anywhere.
- GLOBAL BACKGROUND: html[data-mbackdrop] (app.js BACKDROPS, Customise "Background") styles the host <div class="ms-lights" aria-hidden="true"> with six <i class="l1">..<i class="l6"> that every machine screen carries as its first child, and the phone's host inside .m-bg (parts/phone.html). Pages keep their own grounds light enough for it to show.
- SPACING SCALES: phone .m-app { --m-gut --m-sec-gap --m-group-gap --m-item-gap --m-pad } (mpages/_shared.css); machine .mscreen { --ms-gut --ms-sec-gap --ms-group-gap --ms-item-gap --ms-pad } (mscreens/_space.css). Use them for margins and gaps.
- REAL PHOTOS: showcase/assets/photos/lib/*.jpg with manifest.json (subject, tags, orientation, focal point for object-position), gathered right now by another agent; if the manifest is not there yet, build structure first and come back to photos before you finish. Also assets/photos/*.jpg (Sara's replay stills), assets/app/avatars/*.jpg, assets/app/feed/*.jpg, assets/case/*.jpg. Do not use assets/mscreens/boxer-gym.jpg or boxer-gym-gold.jpg in anything new.
- ICONS: <span data-lucide="trophy"></span> draws any Lucide icon at 1em in currentColor (showcase/lucide.js, painted on load and whenever added). To add one: save https://cdn.jsdelivr.net/npm/lucide-static@1.47.0/icons/NAME.svg into showcase/assets/icons/lucide/ and run \`node tools/build-lucide.mjs\` from ${P}. The phone's older <span data-icon="key"> (app-icons.js) still works.
- HOW-TO ART: showcase/assets/howto/howto-wide-dark.png and -light.png (1568 x 760) and step-1..3-dark/light.png (720 x 720), original illustrations of our machine and phone (from another agent; if they are not there yet, come back to them before you finish).
- MONSTER ENERGY is the sponsor. Its kit is in mscreens/_ads.css (.mon-claw, .mon-word, --mon-green near #95D600, --mon-black); draw original claw marks and a heavy MONSTER wordmark, never a real logo file.

TOOLS: node tools/shoot.mjs <url> <outDir> <width> <height> <plan.json> (steps {wait}, {eval}, {click: selector} a REAL mouse click, {key}, {shot: name, clip?, full?, scale?}; prints console errors; REDUCED_MOTION=1 emulates reduced motion). Write plans with the Write tool; eval steps share one scope, never redeclare a const across steps. Start every plan with {eval: "localStorage.clear(); location.reload(); 1"}, {wait: 4200}. For the machine: window.showcase.mode('machine'), hide .topbar (visibility hidden), zoom 30 (window.showcase.zoom(30)), clip #machine by its getBoundingClientRect; close-ups at zoom 50. For the phone: the device is #device. The embed: http://localhost:5770/?embed=machine&follow=0 at 300 x 1066. Open PNGs with the Read tool and LOOK; make contact sheets with Python PIL (python, not py) to save calls.

HOUSE RULES: no em or en dashes in visible copy; numerals only where they are content (scores, ranks, times, prices, counts that matter), never decorative numbering; a hairline or bar between two words reads as a dash (except the red rules the user's own Figma draws on the phone); no emoji; no gradient text; not everything centred; visible focus; reduced motion keeps everything readable and still; colour and type through tokens so every look works; nothing clipped, cut or colliding; copy is short, specific, in the product's voice (British spelling as the showcase uses).

HOW TO WORK: usage limits have killed runs before, so make your work durable: land each section in the files as soon as it works, and right after each piece append a short entry to ${P}/build/review/LOG_FILE (what, where, how verified) with a Bash append. Edit ONLY your files; anything else goes in the log under "For others" and in your reply. Use Edit (never Write) on any file another builder may also touch (mobile.js, styles.css, index.html, app.js). Aim for about 110 tool calls; prefer contact sheets over single shots; verify with real clicks through the Customise rows (#pageRows .sec-row .sec-btn[data-dir="1"]).
`

const MACHINE = `
YOU BUILD MACHINE SCREENS. Each screen is ONE frame (keep the root element's size and its three shared parts: the backdrop host .ms-lights as the first child, the header <!-- include:parts/ms-brand.html --> right after it (a global section by the chrome builder: its wrapper header.ms-head is display: contents and its designs lay out where the old .ms-brand sat, so replace your screen's own copy of the lockup with this include), and the sponsor strip <!-- include:parts/ms-ad.html --> as the last child; exclude .ms-head as you exclude .ms-brand and .ms-ad in your selectors) with its sections stacked between the header and the strip on the 1080 x 3840 glass, using the --ms-* spacing scale. Each section at least FIVE designs. Readable from 1 to 1.5 m (body text at least 40 px, labels 32 px); the most important thing big; motion that starts on "mscreen" and restarts on "psec", calm under reduced motion. The glass has no touch. Verify every design of every section in the four looks (contact sheets at zoom 30, close-ups at zoom 50) and in the embed; check the Customise rows page through all designs.`

const PHONE = `
YOU BUILD PHONE PAGES. Each page's sections sit in the page's scroll (or fixed) layout on the phone (iPhone 440 x 956 and Android 412 x 915, Customise, Phone), with the --m-* spacing scale, the status bar and the tab bar clear. Each section at least FIVE designs. Tap targets at least 44 px; real photos and icons where they carry meaning; motion on "mpage" and "psec", calm under reduced motion. mobile.js holds the flow logic (go, announce to the machine, credits, the leaderboard, the feed, the reel); page-specific behaviour for new designs goes in mpages/KEY.js and mpages/KEY.css (create them; add <script src="mpages/KEY.js"></script> after the existing mpages/default.js line in index.html with Edit). Edit mobile.js only inside the functions for your pages, with Edit. Verify every design of every section in the four looks and both phones, with real clicks through the page's own controls and the Customise rows.`

const TASKS = [
  { log: 'log-r6-chrome.md', label: 'machine chrome, backgrounds, QR', prompt: `
YOUR AREA: what every screen shares. FILES YOU OWN: mscreens/_backdrops.css, mscreens/_backdrops.js, mscreens/_ads.css, mscreens/_ads.js, parts/ms-ad.html, a new parts/ms-brand.html (with its styles in a new mscreens/_brand.css), qr.css and qr.js (the shared QR), the .m-bg block of parts/phone.html and its rules in mobile.css (Edit), the BACKDROPS list in app.js (Edit, that constant only), and the QR drawing in app.js drawQR (the Result screen's [data-qr]), case-diagrams / ds files only where they draw a QR.
1. GLOBAL BACKGROUND for both surfaces (the user: "make a global background style we have in app and machine ... in customise to change them"). Make the backgrounds much better and give the phone the same ones: the phone's .m-bg gets the same host (six <i>) styled by the same rules, scaled to the phone. Keep the keys lights, beams, pulse, embers, grid (improve each), and add at least two more (for example the phone's own red glow as "Glow", and "Smoke" or "Neon"), so the Background row has at least seven. Subtle behind content, never competing with scores, all four looks, reduced motion still. Default stays calm.
2. MACHINE HEADER as a global section: parts/ms-brand.html already exists (header.ms-head data-sec="mheader" data-sec-scope="global" data-sec-for="machine", display: contents, with the old lockup as its first design "Lockup"); the screen builders are switching their screens to include it right now. Add at least four more designs (styles in mscreens/_brand.css): for example the lockup with the venue and a live clock, a slim top bar, a centred crest, a split with a live dot and the machine number. Each must sit in the same band as the old header (--ms-brand-top, --ms-brand-h in styles.css) so no screen's layout moves. Do not edit the screens' parts; list any screen still carrying its own lockup under "For others".
3. SPONSOR STRIP as a global section: the outer aside.ms-ad of parts/ms-ad.html becomes the section itself (add data-sec="sponsor" data-sec-scope="global" data-sec-for="machine" data-sec-label="Sponsor strip (machine)" to it, so every .ms-ad selector keeps working) with five Monster Energy strip designs as its [data-sv] children (the GIF style loop you have, plus four more creatives, each with a Monster green call to action, stepped GIF rhythm, calm under reduced motion). Same 140 px height and position on every screen.
4. QR EVERYWHERE: make qr.css match the phone's scan tile exactly in all four looks at every size (check a 217 px tile on the phone against a 900 px tile on the glass), switch the Result screen's run code ([data-qr] in sections/*.html, drawn by app.js drawQR) to PunchQR with sizes that fit each design, and the design system's and case study's QR samples. Grep for every other QR drawing (QR_MATRIX users) and list the ones owned by screen builders under "For others".
Verify on every flow screen and phone page in all four looks with each background.` },
  { log: 'log-r6-mdefault.md', label: 'machine Default', prompt: MACHINE + `
YOUR SCREEN: default (NEW, the glass at rest, the first screen of the machine). FILES YOU OWN: parts/mscreen-default.html, mscreens/default.css, mscreens/default.js.
Sections (at least five designs each): "Top ad": a big Monster Energy ad at the top of the glass, a DIFFERENT ad from the sponsor strip (the strip is a 140 px GIF style banner; yours is a large animated hero ad, for example the can with claw scratches tearing through, a lightning strike across the glass, the claw drawn stroke by stroke, a taste of the flavours, a "fuel your strike" offer with a green call to action; original drawing, no logo files). "Welcome": the call to play with the QR in the shared style (Scan to play, three credits, where to stand). "Today's best": the best hits today with real photos of players and scores through PunchFormat. "How it works": scan, top up, punch, in three steps (the how-to art or icons). Add a fifth section if it earns its place (for example a live "Just now" of the last hit). The screen must read as a calm, confident home: the ad owns the top, the call to play is unmissable.` },
  { log: 'log-r6-pdefault.md', label: 'phone Default (Home)', prompt: PHONE + `
YOUR PAGE: default (NEW, the app's home, reached by the tab bar's Home and the first page on load). FILES YOU OWN: parts/mpage-default.html, mpages/default.css, mpages/default.js.
Sections (at least five designs each): "Greeting" (the player, credits in the wallet, notifications), "Play card" (the big way to punch: Scan to play with the nearest machine, opens the scan page; credits state), "Your last hit" (the score through PunchFormat, the replay still, opens Your hit), "Machines near you" (real venue photos, distance, queue; Dubai Mall, Mall of the Emirates, City Walk, Dubai Marina Mall), "From your friends" (a strip of friends' hits with avatars, opens the feed), and a "Monster Energy" promo (a sponsored card with a Monster green call to action, labelled Sponsored). Real photos and icons throughout; a rich, well spaced home.` },
  { log: 'log-r6-reel.md', label: 'phone reels', prompt: PHONE + `
YOUR PAGE: reel. FILES YOU OWN: parts/mpage-reel.html, mpages/reel.css, mpages/reel.js, and the reel's code in mobile.js (renderReel and its helpers, Edit only) and its rules in mobile.css (Edit only).
The user said: "in reels we don't need the slider on the right: remove it, and reels are unlimited scroll; also have settings, and in the reel also a three dots menu." So: remove .m-reel-nav (the up and down buttons with the dots) entirely. Make the reel an endless vertical feed (scroll snap, one attempt per screen, the next ones load as you near the end, from the player's attempts then everyone's, with real photos and varied data; wheel, touch swipe and the arrow keys move between them). Add a settings button that opens a sheet (autoplay, slow motion replays, show scores with decimals follows Score format, captions, data saver, who can see my hits) and a three dots menu on each attempt (Save the clip, Share, Copy link, Hide this player, Report). Keep the like, comment and share rail and the details: score, when, where, the video progress.
Sections (at least five designs each): "Overlay" (how the player, score, when and where sit over the clip), "Actions" (the rail or bar of like, comment, share, the three dots), "Progress" (how the clip's progress and the slow motion are shown). Verify an endless scroll of at least thirty attempts, the settings sheet and the menu with real clicks.` },
  { log: 'log-r6-attract.md', label: 'machine leaderboard', prompt: MACHINE + `
YOUR SCREEN: attract (Leaderboard between players; the user earlier asked it to look like the phone's leaderboard while keeping its structure: a title, the top three, ranks 4 to 10, a call to play). FILES YOU OWN: parts/mscreen-attract.html, mscreens/attract.css, mscreens/attract.js.
Rebuild as one frame with sections (at least five designs each): "Title" (the board's name, the Global, National and Dubai cycle with its time left), "Top three" (cards, podium, champion banner, meter, tiles: the phone's five board styles scaled for the glass), "Ranks 4 to 10" (five row styles), "Call to play" (the QR in the shared style with a short line and a You row). Harvest the three existing designs (As drawn, Podium, Force meter) as designs of these sections. Real player photos (avatars and the photo library), scores through PunchFormat.` },
  { log: 'log-r6-hitranks.md', label: 'phone Your hit and Leaderboard', prompt: PHONE + `
YOUR PAGES: hit (Your hit) and ranks (Leaderboard). FILES YOU OWN: parts/mpage-hit.html, parts/mpage-ranks.html, mpages/hit.css, mpages/hit.js, mpages/ranks.css, mpages/ranks.js, and in mobile.js the Your hit and leaderboard code (paintHit, renderBoard, ROW, the search and scope) with Edit only.
Your hit sections (at least five designs each): "Score" (the score through PunchFormat with its grade), "Replay" (the replay card with a real still, opens the reel), "Ranks" (machine, city, country, global), "Stats" (energy, force, speed, acceleration), "Next" (Punch again with credits, share). Leaderboard sections: "Header" (title, live, search, scope switch), "Board" (already five designs as a script-drawn section: keep, improve spacing), "Your place" (the pinned You row, five designs). Better spacing everywhere; real avatars.` },
  { log: 'log-r6-countload.md', label: 'machine Punch now and Reading', prompt: MACHINE + `
YOUR SCREENS: countdown (Punch now, the machine counts 20 seconds; the phone shows no timer) and loading (Reading the strike, hands over to opts.next after about 2.2 s). FILES YOU OWN: parts/mscreen-countdown.html, parts/mscreen-loading.html, mscreens/countdown.css, mscreens/countdown.js, mscreens/loading.css, mscreens/loading.js.
The user said the Punch now background must change and be much better: give the countdown its own stage (light, energy and depth that builds as the seconds drain, red in the last five) layered over the global background, far better than today. Countdown sections (at least five designs each): "Count" (ring, draining column, light drain, and two more), "Call" (the instruction: step up, one full strike, where to hit), "Player" (who is up: avatar, name, their best, credits left). Loading sections: "Reading" (sensor trace, replay saving, verdict, and two more), "Caption" (the line that says what is happening). Keep the 20 s logic, the demo (strike between 12 and 5 s left, then loading with next: 'record'), the hand over timing and the phone link (opts.start, opts.seconds, opts.impactAt).` },
  { log: 'log-r6-feedprofile.md', label: 'phone Feed and Profile', prompt: PHONE + `
A PREVIOUS ATTEMPT at this task was cut off by a usage limit: read your log file (build/review/log-r6-feedprofile.md) and the current state of your files FIRST, keep what is done and working, and finish the rest; do not start over. It had built both pages and verified them on iPhone Arena dark and Android Reference light; check the other looks and phone, the endless reel it opens, and the Sponsored post.
YOUR PAGES: feed and profile. FILES YOU OWN: parts/mpage-feed.html, parts/mpage-profile.html, mpages/feed.css, mpages/feed.js, mpages/profile.css, mpages/profile.js, and in mobile.js the feed and profile code (renderPosts, renderStories, renderProfile) with Edit only.
Feed sections (at least five designs each): "Stories" (the ring of friends' latest hits), "Filter" (Following, Nearby, the machine community), "Posts" (how a hit post shows: photo or replay still, score, reactions, comment), "Sponsored" (the Monster Energy post, labelled Sponsored, Monster green call to action). Profile sections: "Header" (photo, name, city, follow), "Stats" (best, attempts, rank, streak), "Hits" (the grid or list of kept hits that opens the reel), "Badges" (achievements with icons). Real photos throughout.` },
  { log: 'log-r6-mscan.md', label: 'machine Scan', prompt: MACHINE + `
A PREVIOUS ATTEMPT at this task was cut off by a usage limit: read your log file (build/review/log-r6-mscan.md) and the current state of your files FIRST, keep what is done and working, and finish the rest; do not start over. It had barely started, so check parts/mscreen-scan.html is whole before you build on it.
YOUR SCREEN: scan (the glass shows its code; states from opts: waiting, linked, holding while the phone tops up, missed). FILES YOU OWN: parts/mscreen-scan.html, mscreens/scan.css, mscreens/scan.js.
The user said the machine's Scan page must look like the phone app's scan: the phone's QR on its glass tile with the red glow and scan line (the shared PunchQR, large), the same calm dark ground, the same "How to use?" idea. Rebuild as one frame with sections (at least five designs each): "Code" (the PunchQR tile presented five ways: centred with the glow, framed by the phone's corner marks, on a lit stage, beside a live phone mock, with the machine number), "How to" (the new how-to art in assets/howto: wide picture, three steps, icons, a short line, an animated sequence), "Status" (waiting, linked with the player's avatar, holding for a top up, missed: five ways to show the state). Replace qr-howto-machine.png everywhere in your files with the new art.` },
  { log: 'log-r6-pscan.md', label: 'phone Scan and Connect', prompt: PHONE + `
YOUR PAGES: scan and connect. FILES YOU OWN: parts/mpage-scan.html, parts/mpage-connect.html, mpages/scan.css, mpages/scan.js, mpages/connect.css, mpages/connect.js, the How-to sheet (#mSheet in parts/phone.html, Edit only), and in mobile.js the scan, sheet and connect code with Edit only.
The phone's scan tile is the reference QR style: switch it to the shared PunchQR markup (it must look exactly as it does now). Scan sections (at least five designs each): "Code" (the tile with its glow and line, five framings), "Hint" (the line under it and the How to use? pill), "Recent machines" (where you played, real venue photos). The How-to sheet: use the new illustrations in assets/howto (wide and the three steps; its own five designs as a section inside the sheet, data-sec on an element inside the phone page is fine, or make the sheet part of the scan page's sections). Connect sections: "Linking" (Orbit and Brackets exist as a script-driven section in mobile.js CONNECT_STYLES: grow it to five), "Machine" (which machine you are linking to, with its venue photo), "Credit" (the credit held for this turn).` },
  { log: 'log-r6-statscore.md', label: 'machine Ranks and stats, Big score', prompt: MACHINE + `
YOUR SCREENS: stats (Ranks and stats) and score (Big score). FILES YOU OWN: parts/mscreen-stats.html, parts/mscreen-score.html, mscreens/stats.css, mscreens/stats.js, mscreens/score.css, mscreens/score.js.
Stats sections (at least five designs each): "Score" (PunchFormat, decimals smaller), "Ranks" (machine, city, country, global), "Stats" (energy kJ, force kN, speed mph, acceleration m/s², the Result screen's values), "Replay" (a real still of the strike: Sara's replay stills in assets/photos, never the Figma stock photo). Score sections: "Score" (the score as the whole event, five ways), "Ranks", "Photo" (a real photo of the strike, five treatments). Harvest the existing designs.` },
  { log: 'log-r6-punchpay.md', label: 'phone Punch and payment', prompt: PHONE + `
YOUR PAGES: punch (no timer on the phone: it says punch on the machine; the machine counts 20 s), topup, checkout, paid. FILES YOU OWN: parts/mpage-punch.html, parts/phone-pay.html, pay.css, pay.js, mpages/punch.css, mpages/punch.js, and in mobile.js the punch step's code with Edit only.
Punch sections (at least five designs each): "Look up" (the instruction to punch at the machine, with a picture of the machine and where to stand), "Link" (the live link to the machine, the credit held), "Result" (the landed state before Your hit). Top up: "Packs" (credit packs), "Offer" (a Monster Energy bundle or first-time offer). Checkout: "Summary", "Pay with" (Apple Pay or Google Pay by device, card, wallet). Paid: "Confirmation". Keep the flow logic (credits, the empty wallet, time up keeps the credit, announcements to the machine) working end to end.` },
  { log: 'log-r6-recordresult.md', label: 'machine New record and Result', prompt: MACHINE + `
YOUR SCREENS: record (New record) and the Result screen's polish. FILES YOU OWN: parts/mscreen-record.html, mscreens/record.css, mscreens/record.js, sections/*.html and sections/*.css (the Result screen's nine sections).
Record: rebuild as sections (at least five designs each): "Moment" (the celebration: through the line, rollover, burst, and two more), "Score" (the new best through PunchFormat and the old best it beat), "Photo" (a real strike photo, five treatments). REMOVE assets/mscreens/boxer-gym-gold.jpg from every file that uses it (grep the whole showcase) and delete the file; replace it with something better (a real photo from the library, a crop of Sara's replay stills, or a drawn moment).
Result screen: every one of its nine sections must have at least five designs (count them: app.js showcase.slots()), better spacing between and inside sections, the run code in the shared QR style (coordinate with the chrome builder, who switches drawQR; you size the tiles in each design), real photos where the designs show a photo (not the Figma stock photo in new work), all four looks.` },
]

const FINISH = [
  { log: 'log-r6-docs.md', label: 'documents and brief', prompt: `
YOUR AREA: the design system page, the brief drawer and the case study, brought up to date with this round. FILES YOU OWN: parts/ds.html, ds.css, ds.js, parts/brief.html, brief.css, parts/case.html, case.css, case.js, case-diagrams.*.
Also from the chrome builder: ds.js (around its background list) keeps its own copy of the backgrounds with the old five and a 'lights' fallback: it needs all eight from app.js BACKDROPS (Red glow first, the default); and parts/case-run.html's small glass drawings still use assets/mscreens/boxer-gym.jpg: replace it with a still from assets/photos or the library. Add to the design system: the page section model (every page built from sections with at least five designs, Customise "This screen"), the Default pages, the global background (every background shown small, on the glass and the phone), the one QR style (the component at three sizes), the spacing scales (--m-* and --ms-*), the Lucide icon set (a grid of what is used), the photo library (a strip with credits from assets/photos/lib/manifest.json), the Monster Energy sponsor kit (top ad, strip, feed post). Brief drawer: update "How this showcase answers it" with the new pages and links into them (data-go-mode, data-go-mscreen, data-go-page). Case study: update facts (Default pages, sections, backgrounds, QR, reels without end, the Animation bar) and the "How AI was used" note. Check the brief line by line and fix any gap in your files.` },
  { log: 'log-r6-clip.md', label: 'new motion clip', prompt: `
YOUR AREA: the brief's motion deliverable: "one motion clip, 5 to 10 seconds, of the score reveal". The clip in showcase/assets/motion still shows an older design. Render a NEW clip of the live glass as it is now: the Punch now count's last seconds and the strike, Reading the strike, New record, then the Big score (or the Result screen's reveal), using the designs chosen by default. Record it from the showcase itself with headless Chrome (a frame-stepped capture: drive time yourself with a virtual clock or by stepping each screen's timeline, screenshot each frame at the glass's full 1080 x 3840 or at 540 x 1920 and upscale only if needed; never trust fps filters for timing), encode with ffmpeg (H.264, yuv420p, crf 18 or better, faststart) to showcase/assets/motion/reveal-live-1080x3840.mp4 and a 1920 x 1080 presentation cut (the glass beside short beat names) reveal-live-1920x1080.mp4, a poster JPEG for each, and a 960 wide GIF. Keep the old files. Update the Animation tab's clip section in index.html (#animExtra, Edit only) to show the new clip first with a one-line caption, and anim.js if needed. Look at frames of the encoded video against the page to check sharpness and timing. Log each step in the log.` },
  { log: 'log-r6-review-machine.md', label: 'review: machine', prompt: `
YOUR AREA: REVIEW AND FIX the machine after the build: every screen (Default, Leaderboard, Scan, Punch now, Reading, Result, Ranks and stats, Big score, New record), every section, every design (click through the Customise rows), the global header and sponsor strip designs, every background, the four looks, the embed, reduced motion. You may edit machine files (parts/mscreen-*.html, parts/ms-*.html, mscreens/*, sections/*, styles.css machine rules, app.js machine code with Edit). Check: at least five designs in every section; nothing clipped, colliding or overflowing the glass; spacing on the --ms-* scale; every QR in the phone style; no boxer-gym-gold.jpg; scores through PunchFormat with decimals on and off; the flow still runs (countdown 20 s, loading hands over, record then result). Fix the worst first, log each fix, reply with what you fixed and what is left.` },
  { log: 'log-r6-review-phone.md', label: 'review: phone', prompt: `
YOUR AREA: REVIEW AND FIX the phone after the build: every page (Default, Scan, Connect, Punch, Top up, Checkout, Paid, Your hit, Leaderboard, Feed, Profile, Reel), every section and design (click through the Customise rows), both phones, the four looks, the global backgrounds, the tab bar's five styles, reduced motion. You may edit phone files (parts/phone.html, parts/mpage-*.html, parts/phone-pay.html, mpages/*, mobile.css, mobile.js, nav.css, pay.*). Check: at least five designs in every section; spacing on the --m-* scale; tap targets; the QR in the phone style; the reel scrolls without end with settings and the three dots menu, no right slider; the whole flow runs from Default to Your hit (scan, connect, top up when empty, punch with no timer, the machine counts 20 s, reading, record or result, Your hit) in the Animation tab with Start. Fix the worst first, log each fix, reply with what you fixed and what is left.` },
]

const FINAL = { log: 'log-r6-final.md', label: 'final sweep', prompt: `
YOUR AREA: the FINAL SWEEP of the whole showcase after this round, and the user's twelve points (listed above) one by one. You may edit any showcase file with Edit (never rewrite a whole file another builder owns). Check at 1440 x 900, 1920 x 1080 and 390 x 844: the top bar (logo, then the title, the brief and its line under it; tabs; Start and Reset under the tabs only in Animation), the Customise accordions in every tab (This screen follows the page on show and lists every section; shared groups work; nothing has fewer than five designs: sweep window.showcase.sections for every page of both surfaces and window.showcase.slots for the Result), the Default pages, the Animation tab's Start and Reset end to end, the design system, the brief drawer, the case study, no console errors anywhere, no em or en dashes in visible text (sweep document.body.innerText in each tab), no decorative numerals. Fix what you find, log it, and end your reply with a table: each of the user's twelve points, where it is answered, and its state.` }

const run = (t, phaseName, attempt = 1) =>
  agent(HOUSE.replace('LOG_FILE', t.log) + '\n' + t.prompt + '\nWHEN DONE reply with what you built or fixed (matching your log), what you verified, and anything for others.',
    { label: attempt === 1 ? t.label : t.label + ' (retry)', phase: phaseName })
    .then((r) => (r || attempt > 1 ? r : run(t, phaseName, 2)))

// a pool of four builders: a new one starts as soon as one finishes
async function pool(tasks, n, phaseName) {
  const out = new Array(tasks.length)
  let next = 0
  await Promise.all(Array.from({ length: n }, async () => {
    while (next < tasks.length) {
      const k = next++
      out[k] = await run(tasks[k], phaseName)
      log(`${tasks[k].label}: ${out[k] ? 'done' : 'no result'}`)
    }
  }))
  return out
}

const results = {}
phase('Build')
const built = await pool(TASKS, 4, 'Build')
TASKS.forEach((t, i) => { results[t.label] = built[i] })
phase('Finish')
const fin = await pool(FINISH, 4, 'Finish')
FINISH.forEach((t, i) => { results[t.label] = fin[i] })
phase('Final')
results[FINAL.label] = await run(FINAL, 'Final')
return results
