export const meta = {
  name: 'punch-round5',
  description: 'Own designs, loading and backdrops for the machine flow, Monster Energy ads, the phone without a timer, the Animation tab, full brief coverage',
  phases: [
    { title: 'Wave 1', detail: 'machine flow screens: variants of our own, a reading screen, a 20 second countdown' },
    { title: 'Wave 2', detail: 'Monster Energy ads and backdrops; the phone without a timer, the reel, decimals' },
    { title: 'Wave 3', detail: 'result screen decimals; Animation tab, documents and brief coverage' },
    { title: 'Wave 4', detail: 'review and fix across everything' },
  ],
}

const P = 'C:/Claude Database/punch-exercise'
const HOUSE = `
PROJECT: a design showcase for a PunchApp design task done for Robotenc, in ${P}/showcase (vanilla HTML, CSS and JS), served at http://localhost:5770 by \`node tools/serve-showcase.mjs\` (if it does not answer, start it in the background from ${P}). Includes <!-- include:path --> expand server-side (nested); /sections.css and /mscreens.css concatenate showcase/sections/*.css and showcase/mscreens/*.css. THE BRIEF the company gave (read it, the user wants every point covered): C:/Users/Farhan Hosseini/Downloads/product-designer-challenge.md.
THE SHOWCASE NOW: four tabs in the top bar, in this order: Mobile app (the phone alone, the default), Machine screen, Animation (the phone and a live machine side by side plus the score reveal clip), Design system. "The brief" drawer, "Read case study" (an Apple style long read), "Customise" panel. Global THEME html[data-variant="arena|reference"], APPEARANCE html[data-appearance="dark|light"], LOGO (<img data-logo-img> takes the chosen mark; default Fist), SCORE FORMAT html[data-decimals="on|off"] (on by default: the brief's full length 999,999.000 with the three decimals smaller), BACKDROP html[data-mbackdrop="lights|beams|pulse|embers|grid"] for the machine flow screens.
SCORE FORMATTING (use it everywhere a score shows): window.PunchFormat.score(n) gives text ("999,999.000" or "999,999"), .scoreHTML(n) gives markup with the decimals in <span class="dec"> (base style in styles.css: .46em, quieter), .width(n) gives a character count for the big-number sizing rule, .decimals() tells you which, .withDecimals(whole, seed) gives stable decimals for example data. When the format changes, document dispatches "decimals".
MACHINE: a screen bar over the glass switches eight 1080 x 3840 screens: attract (leaderboard between players), scan, countdown (Punch now), loading (NEW: Reading the strike, between the hit and the score), result (#screen, nine configurable sections with designs A to E), stats (ranks and stats), score (big score), record (New record). Each flow screen is an <article class="mscreen" data-mscreen="KEY"> that includes parts/mscreen-KEY.html; its styles are mscreens/KEY.css, its script mscreens/KEY.js. Each screen now pages through DESIGNS: every top-level child of the part with class "msv" and a data-name is one design ("As drawn" is the Figma based one already there); app.js shows the chosen one (Customise, "Machine screens" rows) and dispatches document event "mscreen" with detail { key, opts } where opts.variant is the design index and opts.design its name. Shared parts every design must carry, identical markup and position: the backdrop host <div class="ms-lights" aria-hidden="true"> with six <i class="l1">..<i class="l6"> as the first child (styled per backdrop by mscreens/_backdrops.css), the logo lockup header.ms-brand (copy it from an existing part), and the sponsor slot <!-- include:parts/ms-ad.html --> as the last child (the 140 px strip at the foot, owned by the ads work). Machine tokens and blocks in styles.css (read them), big numbers sized by font-size: min(calc(CAP_PX / var(--cap)), calc(100cqi / (CHARS * var(--num-w)))). Glyphs: window.glyphSVG(name). Lucide line icons in assets/icons/lucide/ (more from https://cdn.jsdelivr.net/npm/lucide-static@1.47.0/icons/NAME.svg). The glass is read from 1 to 1.5 m, spectators 2 to 3 m back; no sound; no touch.
PHONE: parts/phone.html, mobile.css, mobile.js, nav.css, pay.*; window.punchApp: go(page, opts), announce(key, opts) (tells the live machine what to show), leaders(), credits, score, toast, icon, paint, later, onEnter, device().
TOOLS: node tools/shoot.mjs <url> <outDir> <width> <height> <plan.json> ({wait}, {eval}, {click: selector} a REAL mouse click, {key}, {shot: name, clip?, full?, scale?}; prints console errors; REDUCED_MOTION=1 env emulates reduced motion). Write plans with the Write tool; eval steps share one scope, never redeclare a const across steps. Start plans with {eval: "localStorage.clear(); location.reload(); 1"}, {wait: 4200}. Hooks: window.showcase.mode('mobile'|'machine'|'animation'|'system'), .mscreen(key, opts), .theme(), .appearance(), .logo(), .zoom(n); for the machine hide .topbar (visibility hidden), zoom 30, clip #machine by its getBoundingClientRect. Open PNGs with the Read tool and LOOK; contact sheets with Python PIL save tool calls.
FIGMA: file aDk4RGbovg0KKhtUBokHjk (use the Figma MCP only if you need to compare with an existing frame).
HOUSE RULES: no em or en dashes in visible copy; numerals only where they are content; a hairline or bar between two words reads as a dash (except the red rules the user's own Figma draws beside two phone lines); no emoji; no gradient text; not everything centred; visible focus; reduced motion keeps everything readable; tokens for colour and type so every look works (Arena dark and light, Reference dark and light); nothing clipped or colliding.
HOW TO WORK: usage limits have killed earlier runs, so make your work durable: land each piece in the files as soon as it works, and right after each piece append a short entry to ${P}/build/review/LOG_FILE (what, where, how verified) with a Bash append. Aim for about 90 tool calls; prefer contact sheets over single shots. Edit ONLY your files; anything else goes in the log under "For others" and in your reply.
`

const SCREEN_RULES = `
MAKE THE DESIGNS YOUR OWN. The user said the current flow screens copy the reference images and the Figma frames exactly; they want designs of our own, plus loading and backdrops. So keep the existing "As drawn" design as the first choice, and ADD new designs of your own after it for each of your screens, each a genuinely different composition in the product's own language (the Result screen's sections show the range: gauges, towers, slot reels, podiums, ladders, scoreboards, glass panels). Do NOT reuse the Figma's stock photo (assets/mscreens/boxer-gym.jpg) or copy the frames' layouts in your new designs; use the product's own material instead: the machine's replay stills of Sara in the pink hood (assets/photos/*.jpg, crops you make from assets/case/13460163.jpg are fine), type, data, meters, light and motion. Each new design needs its motion on "mscreen" (start when opts.key is yours and opts.variant is that design, stop when another key or design opens), a calm resting state under reduced motion, scores through window.PunchFormat, and all four looks. Scope CSS under .mscreen-KEY and a design class of your own; scope your JS queries to the active design element (article.querySelectorAll(':scope > .msv')[opts.variant]). Verify every design of your screens in all four looks at zoom 30 and in close-ups, and in the embed (http://localhost:5770/?embed=machine&follow=0 at 300 x 1066, then window.showcase.mscreen(KEY)). Check the Customise rows page through your designs (#mflowRows .sec-row[data-mflow=KEY] .sec-btn[data-dir="1"]).`

const WAVES = [
  { phase: 'Wave 1', tasks: [
    { log: 'log-r5-screens-a.md', label: 'screens: leaderboard, scan, reading', prompt: SCREEN_RULES + `
YOUR SCREENS: attract, scan, loading. FILES YOU OWN: parts/mscreen-attract.html, parts/mscreen-scan.html, parts/mscreen-loading.html, mscreens/attract.css, mscreens/attract.js, mscreens/scan.css, mscreens/scan.js, mscreens/loading.css, mscreens/loading.js.
- attract: the user asked that the machine's leaderboard look much more like the phone's leaderboard (see the phone's Leaderboard screen and its five styles: Cards, Champion, Podium, Tiles, Force meter in mobile.css and mobile.js renderBoard) while keeping the structure it has now (a title, the top three, then ranks 4 to 10, a call to play). Restyle the "As drawn" design that way, then add two more designs of your own that borrow two other phone styles (for example Podium and Force meter), scaled for a 1080 x 3840 glass read from a distance. Data from window.punchApp.leaders() with PunchFormat scores; keep the Global, National and Dubai cycle.
- scan: keep "As drawn", add two designs of your own for the same job (get the attempt onto the phone: the QR, how to use it, the waiting, linked, holding and missed states from opts), for example a huge code with the steps as a sequence, or the code on a stage with the queue in mind.
- loading (NEW, "Reading the strike", shown for about 1.5 to 2.5 s between the hit and the score): design three of your own, each a loading moment with weight: the sensor reading (a meter or waveform filling), the replay being saved, the verdict on its way; it must never look stuck, and it should build anticipation for the score. Replace the stub design in parts/mscreen-loading.html (keep the shared parts). When opened with opts.next (a screen key) it hands over to window.showcase.mscreen(opts.next, opts) after its duration; opened from the bar with no opts it loops.` },
    { log: 'log-r5-screens-b.md', label: 'screens: punch now, new record', prompt: SCREEN_RULES + `
YOUR SCREENS: countdown and record. FILES YOU OWN: parts/mscreen-countdown.html, parts/mscreen-record.html, mscreens/countdown.css, mscreens/countdown.js, mscreens/record.css, mscreens/record.js.
- countdown: THE COUNT IS NOW 20 SECONDS and the machine is the only place it shows (the phone just says punch on the machine). Default seconds to opts.seconds || 20 everywhere (the demo from the bar too; its simulated punch lands between 12 and 5 seconds left, and after the hit it opens window.showcase.mscreen('loading', { next: 'record', score }) so the reading screen plays before the record). Make the 20 second count read well: a ring or bar that drains over 20, the last five seconds building urgency. Keep "As drawn" (update it to 20), add two designs of your own (for example a strength column that empties, or a full-glass number with the time as a draining light).
- record: keep "As drawn", add two designs of your own for the moment a new machine best lands (the score through PunchFormat, the old best it beat, celebration with weight but readable from three metres), with confetti or light that calms under reduced motion.` },
    { log: 'log-r5-screens-c.md', label: 'screens: ranks and stats, big score', prompt: SCREEN_RULES + `
YOUR SCREENS: stats and score. FILES YOU OWN: parts/mscreen-stats.html, parts/mscreen-score.html, mscreens/stats.css, mscreens/stats.js, mscreens/score.css, mscreens/score.js (stats.css currently styles both screens through a shared .msr layout: keep that working for the "As drawn" designs).
- stats: keep "As drawn", add two designs of your own showing the score (PunchFormat, decimals smaller), the four ranks (machine, city, country, global) and the four stats (energy kJ, force kN, speed mph, acceleration m/s²) with the same values as the Result screen (stats.js already copies them), for example the stats as a radar or as meters, the ranks as a climbing ladder.
- score: keep "As drawn", add two designs of your own where the score is the whole event (for example the score set across the full glass height, or the score with the charge column rising to it), the three decimals smaller and clearly subordinate.
Also make the "As drawn" designs of both screens show the decimals correctly (smaller, not colliding) when html[data-decimals="on"].` },
  ] },
  { phase: 'Wave 2', tasks: [
    { log: 'log-r5-ads.md', label: 'ads, backdrops and Monster Energy', prompt: `
YOUR AREA: the sponsor slot and the backdrops of the machine flow screens, and the sponsor everywhere. FILES YOU OWN: parts/ms-ad.html, mscreens/_ads.css, mscreens/_ads.js, mscreens/_backdrops.css, mscreens/_backdrops.js, sections/sponsor.html, sections/sponsor.css, sections/photo.html (only for the sponsor name), the .ms-ad and .ms-lights rules at the end of styles.css (move what you need into your files and delete the old rules there).
1. THE SPONSOR IS NOW MONSTER ENERGY DRINKS. The user said the sponsor (WellFit Gym today) is replaced by Monster Energy drinks. Replace every WellFit mention you own (the Result screen's sponsor section designs A to E, the photo section text if it names WellFit, the ad strip image) and list any other file that still says WellFit under "For others".
2. THE AD: design an animated ad for Monster Energy for the machine's sponsor slot, GIF style (a short loop of stepped, punchy frames, like a banner GIF: the can drawn in CSS or SVG, claw-mark scratches, green lightning, a couple of short lines of copy of your own, for example "Refuel between rounds") with a clear CTA in Monster green (use a vivid lime green near #95D600 on black; draw an original claw-scratch mark and a MONSTER ENERGY wordmark in heavy type, do not reproduce the real logo file). The user said "make it better": make the slot a proper media unit, not just a strip: keep the 140 px strip at the foot of every flow screen (same size and position on all), make it readable from a metre (the CTA text at least 28 px), loop it every 6 to 8 s with a GIF-like stepped rhythm, a calm still under reduced motion, and keep a small AD tag. Also give the Result screen's sponsor section (sections/sponsor.*, designs A to E) the Monster Energy brand in each design's own style, within its 120 px height budget (check with node tools/shoot-slot.mjs sponsor both).
3. THE BACKDROPS: in mscreens/_backdrops.css (and _backdrops.js only if needed), style the shared .ms-lights host (six <i> children l1..l6) for each html[data-mbackdrop]: lights (the current six soft pools), beams (stadium light beams sweeping slowly), pulse (a heartbeat of light rising from the base), embers (slow drifting sparks), grid (a perspective arena floor grid). Subtle behind content, never competing with the score, all four looks, reduced motion still. Customise has a Backdrop row in "Machine screens" (#mflowRows .sec-row[data-mflow=backdrop]).
Verify on every flow screen (window.showcase.mode('machine'); window.showcase.mscreen(key)) in all four looks, the embed at 300 x 1066, and the Result screen's sponsor designs.` },
    { log: 'log-r5-phone.md', label: 'phone: no timer, reel, decimals', prompt: `
YOUR AREA: the phone. FILES YOU OWN: parts/phone.html, parts/phone-pay.html, mobile.css, mobile.js, nav.css, pay.css, pay.js.
1. THE PUNCH STEP HAS NO TIMER NOW. The user said: the phone has no timer, it just says punch on the machine; only the machine counts down, and the count is 20 seconds. Remove the countdown number and ring from the phone's punch step; show a clear instruction to punch at the machine (look up at the machine, step up to the bag, one full-force strike), a live "machine linked" state and a calm waiting animation that points to the machine (not a number). Announce the countdown to the machine with seconds: 20 and an impactAt between 5 and 12 s after the start; at the strike the phone shows the landed state, then announce('loading', { next: 'record' or 'result', score }) so the machine plays its new Reading screen (about 2 s) before the record or result, then the phone opens Your hit. Keep Cancel and the time up state (no punch, credit kept) but without numbers.
2. THE REEL (the brief asks for "the player's profile and a reel of their attempts: score, video, when, where"): tapping a hit on the profile opens a full-screen reel of that player's attempts: the video playing (a placeholder: the still with a moving progress bar and a play or pause control), the score with decimals, when (for example "Today, 18:42" or "Tue 16 Sep"), where (the venue and machine), a like and a share, and swipe up or down (and buttons) to move between attempts. Give example data real dates and venues. Your hit's replay card may open the same reel.
3. DECIMALS: use window.PunchFormat for every score on the phone (Your hit card, leaderboard rows in all five styles, feed posts, profile, the reel, the pay screens if any), decimals smaller; re-render on the document "decimals" event. Give the example players decimals with PunchFormat.withDecimals(score, id).
4. SPONSOR: the sponsor is now Monster Energy drinks (it was WellFit Gym). If the phone mentions WellFit anywhere, change it, and add one sponsored post to the feed from Monster Energy with a green CTA (Monster green near #95D600, an original claw mark, no real logo files), clearly labelled Sponsored.
Verify in all four looks on iPhone and Android: the punch step, the reel (open from the profile and from Your hit, move between attempts, like), decimals on and off (Customise, Score format), and in the Animation tab (window.showcase.mode('animation')) that the live machine counts 20 s alone while the phone shows no number, then plays Reading, then record or result.` },
  ] },
  { phase: 'Wave 3', tasks: [
    { log: 'log-r5-result.md', label: 'result screen: full-length scores', prompt: `
YOUR AREA: the Result screen's score with the brief's full length, 0 to 999,999.000 (six digits, a separator and three decimals). FILES YOU OWN: sections/hero.html, sections/hero.css, sections/hero-slot.html, sections/hero-slot.css, sections/ranks.css, sections/stats.css, and in app.js ONLY paintScore, setReels, countUp and the score slider's formatting (search for them), plus the design A hero rules in styles.css (.hero-score and its Reference override).
Make every score on the Result screen use window.PunchFormat (paintScore should write PunchFormat.scoreHTML into [data-bind="score"] elements), with the three decimals smaller and clearly subordinate to the whole number, and make all six hero designs (A to F, including the slot reels, which need three small decimal reels or a small static decimal tail) fit and look designed at full length, in all four looks and at breathing room 70, 100 and 125 (node tools/shoot-slot.mjs hero both reports overflow and height against a 640 px budget), with decimals on and off (html[data-decimals]). The Customise Score slider should move in whole points but the displayed score keeps its decimals (the default score is 999,999.000). The count-up should count the decimals too at the end. Check the Reference theme's design A as drawn still reads right.` },
    { log: 'log-r5-docs.md', label: 'animation tab, documents, brief coverage', prompt: `
YOUR AREA: the Animation tab, the design system page's width and content, the brief drawer, the case study copy, and a full audit that the brief is covered. FILES YOU OWN: the Animation tab markup in index.html (#animExtra and the phone stage's is-anim layout) and its styles (you may add a new file anim.css and link it in index.html head, and anim.js before app.js), ds.css, ds.js, parts/ds.html, parts/brief.html, brief.css, parts/case.html, case.css, case.js, and in app.js only the MODE_TEXT copy and syncLinked.
1. ANIMATION TAB (window.showcase.mode('animation')): the phone and the live machine (#linked, an iframe of ./?embed=machine) side by side, large and centred, with a clear "Play the whole flow" control that runs it automatically (credits to 3 if empty, scan, connect, the machine's 20 s countdown, the strike, Reading, record or result, Your hit) and a Reset; captions under each surface saying what it is showing; the score reveal clip (assets/motion/reveal-presentation-1920x1080.mp4, also reveal-master-1080x3840.mp4 and reveal-presentation-960.gif exist) presented as the brief's motion deliverable with a short caption. It must work from 1024 to 1920 wide (stack the machine under the phone when side by side does not fit) and stay out of the Mobile app tab, which shows only the phone.
2. DESIGN SYSTEM: the user said its main container is too wide: make it the same comfortable width as the other tabs (ds.css max-width is now 1040 px; check it reads well, tighten further if needed). Add what is new: the score format (999,999.000 with smaller decimals), the backdrops, the sponsor slot and Monster Energy as the sponsor, the machine flow screens and their designs.
3. BRIEF COVERAGE: go through every line of the brief (C:/Users/Farhan Hosseini/Downloads/product-designer-challenge.md) and make sure the showcase answers it, and that the brief drawer's "How this showcase answers it" block maps each point to where it lives, with buttons into the right tab: the score as an event (the reveal, slot reels, the reading screen, new record), the playback (the replay video section and the reel), making the player go again (Punch again, credits), the machine to phone handoff (Scan, the live link, the phone's punch step), the profile and reel of attempts with score, video, when and where, the social layer (feed, reactions, following, stories, the machine community), competition (leaderboards on both surfaces and why), the 1080 x 3840 screen, 1.5 m panel, score range 0 to 999,999.000 (the Score format control), the touch decision (the machine assumes no touch: say it and why), viewing distances, no audio, unattended all day (attract loop, faults in the state diagram), the phone platform and frame sizes (iPhone 17 Pro Max 440 x 956 and Android 412 x 915), the brand tokens and what changed, the deliverables (the Figma file aDk4RGbovg0KKhtUBokHjk, the motion clip, the half page of notes with decisions, validation and pushback), and the AI note (where AI tools were used and what was changed afterwards). Fix gaps in your files and list gaps elsewhere.
4. CASE STUDY COPY: update facts to the current product: the tab order, the machine flow with the Reading screen and screen designs, the 20 second count on the machine only, the phone without a timer, the reel, Monster Energy as the sponsor with the animated ad, the backdrops, the score format, the Animation tab, and an explicit "How AI was used" that names where and what was changed afterwards.
Verify the Animation tab end to end with real clicks at 1440 x 900 and 1920 x 1080 and 1024 x 768, the design system at 1440 and 390, the brief drawer and the case study.` },
  ] },
  { phase: 'Wave 4', tasks: [
    { log: 'log-r5-review-machine.md', label: 'review: machine and animation', prompt: `
YOUR AREA: REVIEW AND FIX the machine side after the build: every flow screen and every design in Customise (#mflowRows), in all four looks and five backdrops, the ads, the Result screen with decimals on and off, and the Animation tab running the whole flow. You may edit machine files (sections/*, parts/mscreen-*, parts/ms-ad.html, mscreens/*, styles.css machine rules, app.js machine flow code). Fix what is broken or clearly weak, worst first, log each fix. Also check shared parts are identical across all designs of all flow screens (logo lockup, sponsor slot, backdrop host) and that nothing from other stylesheets leaks into them (read computed styles).` },
    { log: 'log-r5-review-phone.md', label: 'review: phone, documents, brief', prompt: `
YOUR AREA: REVIEW AND FIX the phone, the design system page, the brief drawer and the case study after the build, and confirm the brief (C:/Users/Farhan Hosseini/Downloads/product-designer-challenge.md) is covered point by point. You may edit phone files (parts/phone*.html, mobile.*, nav.css, pay.*), ds.*, parts/ds.html, parts/brief.html, brief.css, parts/case.html, case.*, anim.* and index.html. Check: the tab order (Mobile app, Machine screen, Animation, Design system) and that Mobile app shows only the phone; the punch step has no number; the reel; decimals on and off; the Monster sponsored post; the design system width; copy house rules (no dashes, no decorative numerals) across the new text; no console errors. Fix, log, and end your reply with a table of every brief point and where it is answered.` },
  ] },
]

const run = (t, phaseName) => agent(HOUSE.replace('LOG_FILE', t.log) + '\n' + t.prompt + '\nWHEN DONE reply with what you built or fixed (matching your log), what you verified, and anything for others.', { label: t.label, phase: phaseName })

const out = {}
for (const w of WAVES) {
  phase(w.phase)
  const res = await parallel(w.tasks.map((t) => () => run(t, w.phase)))
  w.tasks.forEach((t, i) => { out[t.label] = res[i] })
}
return out
