// Packs every Lucide icon in showcase/assets/icons/lucide (ISC licence, lucide.dev) into showcase/lucide.js, so any page
// can draw one by name: <span data-lucide="trophy"></span>. Run it again after adding an SVG to that folder.
import { readFile, readdir, writeFile } from 'node:fs/promises'
const dir = new URL('../showcase/assets/icons/lucide/', import.meta.url)
const names = (await readdir(dir)).filter((n) => n.endsWith('.svg')).sort()
const out = {}
for (const n of names) {
  const svg = await readFile(new URL(n, dir), 'utf8')
  const body = (svg.match(/<svg[^>]*>([\s\S]*)<\/svg>/) || [])[1] || ''
  out[n.slice(0, -4)] = body.replace(/<!--[\s\S]*?-->/g, '').replace(/\s+/g, ' ').replace(/ \/>/g, '/>').trim()
}
const js = `/* Generated by tools/build-lucide.mjs from assets/icons/lucide (Lucide, ISC licence). Do not edit by hand.
   <span data-lucide="trophy"></span> is filled with that icon at 1em, in currentColor, on load and whenever such an
   element is added to the page. window.lucide(name, { size, stroke }) returns the markup for script-built HTML. */
window.LUCIDE = ${JSON.stringify(out)};
(() => {
  'use strict'
  function lucide(name, opts = {}) {
    const body = window.LUCIDE[name]
    if (!body) return ''
    const size = opts.size || '1em', sw = opts.stroke || 1.75
    return '<svg class="ico lucide" viewBox="0 0 24 24" width="' + size + '" height="' + size + '" aria-hidden="true" focusable="false" fill="none" stroke="currentColor" stroke-width="' + sw + '" stroke-linecap="round" stroke-linejoin="round">' + body + '</svg>'
  }
  function paint(root) {
    if (!root || !root.querySelectorAll) return
    const list = root.matches && root.matches('[data-lucide]') ? [root] : []
    list.push(...root.querySelectorAll('[data-lucide]'))
    for (const el of list) {
      if (el.dataset.lucidePainted === el.dataset.lucide) continue
      el.innerHTML = lucide(el.dataset.lucide, { size: el.dataset.lucideSize, stroke: el.dataset.lucideStroke })
      el.dataset.lucidePainted = el.dataset.lucide
    }
  }
  window.lucide = lucide
  window.paintLucide = paint
  const start = () => {
    paint(document.body)
    new MutationObserver((muts) => { for (const m of muts) for (const n of m.addedNodes) if (n.nodeType === 1) paint(n) })
      .observe(document.body, { childList: true, subtree: true })
  }
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', start)
  else start()
})()
`
await writeFile(new URL('../showcase/lucide.js', import.meta.url), js)
console.log('lucide', names.length, 'icons', (js.length / 1024).toFixed(1) + ' KB')
